{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "pythonVersion": "3.11"  # Add this line to specify Python 3.11
  },
  "deploy": {
    "startCommand": "gunicorn config.wsgi",
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10
  }
}
