# Generated by Django 5.0.2 on 2024-03-02 11:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_settings_address_alter_settings_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contactus',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
