# Generated by Django 5.0.2 on 2024-03-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contactmodel_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='message',
            new_name='messages',
        ),
    ]
